library(googleVis)

Motion=gvisMotionChart(Fruits, 
                       idvar="Fruit", 
                       timevar="Year")
plot(Motion)

??gvisorgchart
## Please note that by default the googleVis plot command
## will open a browser window and requires Internet
## connection to display the visualisation.

d <- Regions
d$Val <- MHmakeRandomString()
d
Regions <- d
Org1 <- gvisOrgChart(Regions, idvar = "Region", parentvar = "Parent",
                     tipvar="Val")
plot(Org1)

## Set a few options
Org2 <- gvisOrgChart(Regions, idvar = "Region", parentvar = "Parent",
                     tipvar="Val",
                     options=list(width=600, height=400,
                                  size='large', allowCollapse=TRUE))
plot(Org2)


MHmakeRandomString <- function(n=1, lenght=12)
{
  randomString <- c(1:n)                  # initialize vector
  for (i in 1:n)
  {
    randomString[i] <- paste(sample(c(0:9, letters, LETTERS),
                                    lenght, replace=TRUE),
                             collapse="")
  }
  return(randomString)
}

MHmakeRandomString()
